### ISSUE TITLE
Provide compiled binaries targeted for .NET 4.x

### ISSUE THREAD

**Issue by chryzsh** [r3motecontrol/Ghostpack-CompiledBinaries#1]
Hi. I use this repo regularily, but often stumble upon boxes that don't have .NET 3.5. Would you be willing to add 4.x compiled binaries as well? That would be awesome. 🥇

**Comment by r3motecontrol** [comment]
@chryzsh sure I will compile and upload them to this repo by tomorrow.

**Comment by r3motecontrol** [comment]
@chryzsh I modified the target framework to v4.5 and uploaded the binaries. Can you please verify whether they are working.

Let me know if you want me to upload binaries for a specific version, e.g. 4.6, 4.8 etc

**Comment by chryzsh** [comment]
As expected it works great. Thank you!
