### ISSUE TITLE
Request for compiled binaries from different repository

### ISSUE THREAD

**Issue by NotoriousRebel** [r3motecontrol/Ghostpack-CompiledBinaries#2]
This project is great! I was wondering how hard it would be to add these?
https://github.com/FuzzySecurity/Sharp-Suite
This is from a different repo but very useful as well. Might be worth as a new repository or new folder?

**Comment by r3motecontrol** [comment]
@NotoriousRebel thanks for the feedback.
I created a new repo for sharp suite
https://github.com/r3motecontrol/Sharp-Suite-CompiledBinaries
I will add rest of the binaries by weekend/next week.

**Comment by r3motecontrol** [comment]
@NotoriousRebel I added rest of the binaries to the new repository.
