### ISSUE TITLE
Thoughts on adding Inveigh.exe

### ISSUE THREAD

**Issue by A1vinSmith** [r3motecontrol/Ghostpack-CompiledBinaries#3]
Hello there,

How about adding Inveigh.exe to the repo? Is there any obstacles or welcome a PR for that?

Kind regards,

**Comment by r3motecontrol** [comment]
My apologies for the late response. 

If you are referring to this [repository](https://github.com/Kevin-Robertson/Inveigh/), then the compiled binaries are already available. You can access them [here](https://github.com/Kevin-Robertson/Inveigh/releases/tag/v2.0.5)

Cheers

**Comment by A1vinSmith** [comment]
Thank you!
