### ISSUE TITLE
Compiling by latest .NET Framework version (4.8.1)

### ISSUE THREAD

**Issue by D3vil0p3r** [r3motecontrol/Ghostpack-CompiledBinaries#5]
Hey @r3motecontrol 
can you provide compiled binaries by .NET Framework 4.8.1 (latest)?

**Comment by r3motecontrol** [comment]
Hey @D3vil0p3r, Sorry for the late reply, I will try to upload them by this weekend

**Comment by r3motecontrol** [comment]
Added them. 

[4.8.1 binaries](https://github.com/r3motecontrol/Ghostpack-CompiledBinaries/tree/master/dotnet%20v4.8.1%20compiled%20binaries)

**Comment by D3vil0p3r** [comment]
Thank you
